version: '3.7'

services:
  app:
    container_name: library_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    depends_on:
      - mySql
      - redis

  mySql:
    image: mysql:5.7
    container_name: library_db
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'

  redis:
    image: 'redis:alpine'
    container_name: library_redis
    ports:
      - '6379:6379'
